package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"errors"
	"inventarios/database/auth/roles"
	"inventarios/database/auth/rolpermiso"
	"inventarios/database/auth/usuarios"
	"inventarios/database/auth/xauth"
	"inventarios/graph/model"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, username string, password string) ([]*model.Rol, error) {
	return xauth.Login(ctx, r.DB, username, password)
}

// UseRol is the resolver for the useRol field.
func (r *mutationResolver) UseRol(ctx context.Context, username string, password string, rolID string) (*model.UsuarioLogin, error) {
	return xauth.UseRol(ctx, r.DB, username, password, rolID)
}

// CreateUsuario is the resolver for the createUsuario field.
func (r *mutationResolver) CreateUsuario(ctx context.Context, input model.NewUsuario) (*model.Usuario, error) {
	data, err := xauth.CtxValueApp(ctx, r.DB, "createUsuario")
	if data == nil {
		return nil, errors.New(err.Error())
	}
	return usuarios.CreateUsuario(r.DB, input)
}

// UpdateUsuario is the resolver for the updateUsuario field.
func (r *mutationResolver) UpdateUsuario(ctx context.Context, input model.UpdateUsuario) (*model.Usuario, error) {
	data, err := xauth.CtxValueApp(ctx, r.DB, "updateUsuario")
	if data == nil {
		return nil, errors.New(err.Error())
	}
	return usuarios.UpdateUsuario(r.DB, input)
}

// CreateRol is the resolver for the createRol field.
func (r *mutationResolver) CreateRol(ctx context.Context, input model.NewRol) (*model.Rol, error) {
	data, err := xauth.CtxValueApp(ctx, r.DB, "createRol")
	if data == nil {
		return nil, errors.New(err.Error())
	}
	return roles.CreateRol(r.DB, input)
}

// DeleteRol is the resolver for the deleteRol field.
func (r *mutationResolver) DeleteRol(ctx context.Context, rolID string) (bool, error) {
	data, err := xauth.CtxValueApp(ctx, r.DB, "deleteRol")
	if data == nil {
		return false, errors.New(err.Error())
	}
	return roles.DeleteRol(r.DB, rolID)
}

// ModificarRol is the resolver for the modificarRol field.
func (r *mutationResolver) ModificarRol(ctx context.Context, input model.UpdateRol) (*model.Rol, error) {
	data, err := xauth.CtxValueApp(ctx, r.DB, "modificarRol")
	if data == nil {
		return nil, errors.New(err.Error())
	}
	return roles.ModificarRol(r.DB, input)
}

// UsuarioByUsername is the resolver for the usuarioByUsername field.
func (r *queryResolver) UsuarioByUsername(ctx context.Context, username string) (*model.UsuariosResponse, error) {
	data, err := xauth.CtxValue(ctx, r.DB, "usuarioByUsername")
	if data == nil {
		return nil, errors.New(err.Error())
	}
	return usuarios.UsuarioByUsernameRoles(r.DB, username)
}

// Permisos is the resolver for the permisos field.
func (r *queryResolver) Permisos(ctx context.Context) ([]*model.RolPermiso, error) {
	data, err := xauth.CtxValue(ctx, r.DB, "permisos")
	if data == nil {
		return nil, errors.New(err.Error())
	}
	return rolpermiso.Permisos(r.DB)
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context, lite bool) ([]*model.RolResponse, error) {
	data, err := xauth.CtxValueApp(ctx, r.DB, "roles")
	if data == nil {
		return nil, errors.New(err.Error())
	}
	return roles.Listar(r.DB, lite)
}

// Usuarios is the resolver for the usuarios field.
func (r *queryResolver) Usuarios(ctx context.Context) ([]*model.UsuariosResponse, error) {
	data, err := xauth.CtxValueApp(ctx, r.DB, "roles")
	if data == nil {
		return nil, errors.New(err.Error())
	}
	return usuarios.Usuarios(r.DB)
}

// PermisosByRol is the resolver for the permisosByRol field.
func (r *queryResolver) PermisosByRol(ctx context.Context, rolID string) ([]*model.RolPermiso, error) {
	data, err := xauth.CtxValueApp(ctx, r.DB, "permisosByRol")
	if data == nil {
		return nil, errors.New(err.Error())
	}
	return rolpermiso.PermisosByRol(r.DB, rolID)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
