// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CategoriaVehiculosResponse struct {
	ID          string `json:"id"`
	Nombre      string `json:"nombre"`
	Descripcion string `json:"descripcion"`
	Vehiculos   int    `json:"vehiculos"`
}

type ConductorVehiculos struct {
	UsuarioID  string    `json:"usuario_id"`
	VehiculoID string    `json:"vehiculo_id"`
	Estado     bool      `json:"estado"`
	Registrado time.Time `json:"registrado"`
}

type CreateCategoriaVehiculos struct {
	ID          *string `json:"id,omitempty"`
	Nombre      string  `json:"nombre"`
	Descripcion string  `json:"descripcion"`
}

type CreateConductorVehiculos struct {
	UsuarioID  string `json:"usuario_id"`
	VehiculoID string `json:"vehiculo_id"`
}

type CreateDirecciones struct {
	ID          *string `json:"id,omitempty"`
	Nombre      string  `json:"nombre"`
	Descripcion string  `json:"descripcion"`
	Latitud     float64 `json:"latitud"`
	Longitud    float64 `json:"longitud"`
	UsuarioID   string  `json:"usuario_id"`
}

type CreateVehiculos struct {
	ID          *string `json:"id,omitempty"`
	Placa       string  `json:"placa"`
	Puertas     int     `json:"puertas"`
	Capacidad   int     `json:"capacidad"`
	Descripcion string  `json:"descripcion"`
	Color       string  `json:"color"`
	Modelo      string  `json:"modelo"`
	Anio        int     `json:"anio"`
	CategoriaID string  `json:"categoria_id"`
	FotoURL     *string `json:"foto_url,omitempty"`
}

type CreateViajes struct {
	PasajeroID  string   `json:"pasajero_id"`
	Descripcion string   `json:"descripcion"`
	CategoriaID string   `json:"categoria_id"`
	OrigenLat   float64  `json:"origen_lat"`
	OrigenLon   float64  `json:"origen_lon"`
	DestinoLat  *float64 `json:"destino_lat,omitempty"`
	DestinoLon  *float64 `json:"destino_lon,omitempty"`
}

type CreateViajesLocations struct {
	ViajeID  string  `json:"viaje_id"`
	Latitud  float64 `json:"latitud"`
	Longitud float64 `json:"longitud"`
}

type Direcciones struct {
	ID          string    `json:"id"`
	Nombre      string    `json:"nombre"`
	Descripcion string    `json:"descripcion"`
	Latitud     float64   `json:"latitud"`
	Longitud    float64   `json:"longitud"`
	Estado      bool      `json:"estado"`
	UsuarioID   string    `json:"usuario_id"`
	Registrado  time.Time `json:"registrado"`
}

type NewRol struct {
	Nombre   string   `json:"nombre"`
	Permisos []string `json:"permisos"`
}

type NewUsuario struct {
	Nombres   string     `json:"nombres"`
	Apellidos string     `json:"apellidos"`
	Username  string     `json:"username"`
	Documento string     `json:"documento"`
	Password  *string    `json:"password,omitempty"`
	FotoURL   *string    `json:"foto_url,omitempty"`
	Telefono  *string    `json:"telefono,omitempty"`
	Correo    *string    `json:"correo,omitempty"`
	FechaNac  *time.Time `json:"fecha_nac,omitempty"`
	Domicilio *string    `json:"domicilio,omitempty"`
	Roles     []string   `json:"roles"`
}

type QueryFechas struct {
	FechaInicio        string `json:"fecha_inicio"`
	FechaFin           string `json:"fecha_fin"`
	IncludeDisponibles bool   `json:"include_disponibles"`
}

type Rol struct {
	ID     string `json:"id"`
	Nombre string `json:"nombre"`
	Bit    int    `json:"bit"`
}

type RolPermiso struct {
	Metodo      string `json:"metodo"`
	Descripcion string `json:"descripcion"`
	//  los roles que tienen acceso a este permiso, expresado en suma sumaria << bits
	RolBits int `json:"rol_bits"`
}

type RolResponse struct {
	ID       string `json:"id"`
	Nombre   string `json:"nombre"`
	Bit      int    `json:"bit"`
	Permisos int    `json:"permisos"`
	Usuarios int    `json:"usuarios"`
}

type Tokens struct {
	Username   string    `json:"username"`
	Token      string    `json:"token"`
	Registrado time.Time `json:"registrado"`
}

type UpdateRol struct {
	ID       string   `json:"id"`
	Nombre   string   `json:"nombre"`
	Permisos []string `json:"permisos"`
}

type UpdateUsuario struct {
	ID        string     `json:"id"`
	Nombres   string     `json:"nombres"`
	Apellidos string     `json:"apellidos"`
	Username  string     `json:"username"`
	Documento string     `json:"documento"`
	Password  *string    `json:"password,omitempty"`
	FotoURL   *string    `json:"foto_url,omitempty"`
	Telefono  *string    `json:"telefono,omitempty"`
	Correo    *string    `json:"correo,omitempty"`
	FechaNac  *time.Time `json:"fecha_nac,omitempty"`
	Domicilio *string    `json:"domicilio,omitempty"`
	Roles     []string   `json:"roles"`
}

type Usuario struct {
	ID         string     `json:"id"`
	Nombres    string     `json:"nombres"`
	Apellidos  string     `json:"apellidos"`
	Username   string     `json:"username"`
	Telefono   *string    `json:"telefono,omitempty"`
	Documento  string     `json:"documento"`
	Correo     *string    `json:"correo,omitempty"`
	FotoURL    *string    `json:"foto_url,omitempty"`
	FechaNac   *time.Time `json:"fecha_nac,omitempty"`
	Domicilio  *string    `json:"domicilio,omitempty"`
	Registrado time.Time  `json:"registrado"`
	Estado     bool       `json:"estado"`
}

type UsuarioLogin struct {
	ID         string     `json:"id"`
	Nombres    string     `json:"nombres"`
	Apellidos  string     `json:"apellidos"`
	Username   string     `json:"username"`
	FotoURL    *string    `json:"foto_url,omitempty"`
	Telefono   *string    `json:"telefono,omitempty"`
	Correo     *string    `json:"correo,omitempty"`
	Documento  string     `json:"documento"`
	FechaNac   *time.Time `json:"fecha_nac,omitempty"`
	Domicilio  *string    `json:"domicilio,omitempty"`
	Registrado time.Time  `json:"registrado"`
	Estado     bool       `json:"estado"`
	Dataname   string     `json:"dataname"`
	RolID      string     `json:"rol_id"`
	Rol        string     `json:"rol"`
	Exp        string     `json:"exp"`
}

type UsuariosResponse struct {
	ID         string     `json:"id"`
	Nombres    string     `json:"nombres"`
	Apellidos  string     `json:"apellidos"`
	Username   string     `json:"username"`
	FotoURL    *string    `json:"foto_url,omitempty"`
	Telefono   *string    `json:"telefono,omitempty"`
	Documento  string     `json:"documento"`
	FechaNac   *time.Time `json:"fecha_nac,omitempty"`
	Domicilio  *string    `json:"domicilio,omitempty"`
	Correo     *string    `json:"correo,omitempty"`
	Registrado time.Time  `json:"registrado"`
	Estado     bool       `json:"estado"`
	Dataname   string     `json:"dataname"`
	Roles      []*Rol     `json:"roles"`
}

type VehiculosResponse struct {
	ID                      string    `json:"id"`
	Placa                   string    `json:"placa"`
	Puertas                 int       `json:"puertas"`
	Capacidad               int       `json:"capacidad"`
	Descripcion             string    `json:"descripcion"`
	Color                   string    `json:"color"`
	Modelo                  string    `json:"modelo"`
	Anio                    int       `json:"anio"`
	CategoriaID             string    `json:"categoria_id"`
	FotoURL                 *string   `json:"foto_url,omitempty"`
	Estado                  bool      `json:"estado"`
	Registrado              time.Time `json:"registrado"`
	ConductorID             *string   `json:"conductor_id,omitempty"`
	Conductor               *string   `json:"conductor,omitempty"`
	Categoria               string    `json:"categoria"`
	EstadoConductorVehiculo *bool     `json:"estado_conductor_vehiculo,omitempty"`
}

type ViajesLocations struct {
	ID         string    `json:"id"`
	Latitud    float64   `json:"latitud"`
	Longitud   float64   `json:"longitud"`
	ViajeID    string    `json:"viaje_id"`
	Registrado time.Time `json:"registrado"`
}

type ViajesResponse struct {
	ID                string    `json:"id"`
	PasajeroID        string    `json:"pasajero_id"`
	ConductorID       *string   `json:"conductor_id,omitempty"`
	Estado            bool      `json:"estado"`
	Descripcion       string    `json:"descripcion"`
	CategoriaID       string    `json:"categoria_id"`
	OrigenLat         float64   `json:"origen_lat"`
	OrigenLon         float64   `json:"origen_lon"`
	DestinoLat        *float64  `json:"destino_lat,omitempty"`
	DestinoLon        *float64  `json:"destino_lon,omitempty"`
	Registrado        time.Time `json:"registrado"`
	PasajeroUsername  string    `json:"pasajero_username"`
	ConductorUsername *string   `json:"conductor_username,omitempty"`
}
