// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Almacenes struct {
	ID          string    `json:"id"`
	Nombre      string    `json:"nombre"`
	Descripcion string    `json:"descripcion"`
	Registrado  time.Time `json:"registrado"`
}

type Categorias struct {
	ID          string    `json:"id"`
	Nombre      string    `json:"nombre"`
	Descripcion string    `json:"descripcion"`
	Estado      bool      `json:"estado"`
	Registrado  time.Time `json:"registrado"`
}

type DetalleTransacciones struct {
	ID             string  `json:"id"`
	TransaccionID  string  `json:"transaccion_id"`
	ProductoID     string  `json:"producto_id"`
	Cantidad       int     `json:"cantidad"`
	PrecioUnitario float64 `json:"precio_unitario"`
}

type NewAlmacen struct {
	ID          *string `json:"id,omitempty"`
	Nombre      string  `json:"nombre"`
	Descripcion string  `json:"descripcion"`
}

type NewCategoria struct {
	ID          *string `json:"id,omitempty"`
	Nombre      string  `json:"nombre"`
	Descripcion string  `json:"descripcion"`
}

type NewDetalleTransaccion struct {
	ProductoID     string  `json:"producto_id"`
	Cantidad       int     `json:"cantidad"`
	PrecioUnitario float64 `json:"precio_unitario"`
}

type NewPersona struct {
	ID        *string `json:"id,omitempty"`
	Nombres   string  `json:"nombres"`
	Apellidos string  `json:"apellidos"`
	Telefono  string  `json:"telefono"`
	Correo    string  `json:"correo"`
	Direccion string  `json:"direccion"`
	Tipo      string  `json:"tipo"`
}

type NewProducto struct {
	ID            *string `json:"id,omitempty"`
	Nombre        string  `json:"nombre"`
	Codigo        string  `json:"codigo"`
	UnidadMedida  string  `json:"unidad_medida"`
	PrecioEntrada float64 `json:"precio_entrada"`
	PrecioSalida  float64 `json:"precio_salida"`
	CategoriaID   string  `json:"categoria_id"`
}

type NewRol struct {
	Nombre   string   `json:"nombre"`
	Permisos []string `json:"permisos"`
}

type NewTransaccion struct {
	Tipo        string                   `json:"tipo"`
	Descripcion string                   `json:"descripcion"`
	PersonaID   string                   `json:"persona_id"`
	UsuarioID   string                   `json:"usuario_id"`
	Detalles    []*NewDetalleTransaccion `json:"detalles"`
}

type NewUbicacion struct {
	ID         *string `json:"id,omitempty"`
	AlmacenID  string  `json:"almacen_id"`
	ProductoID string  `json:"producto_id"`
	Cantidad   int     `json:"cantidad"`
}

type NewUsuario struct {
	Nombres   string     `json:"nombres"`
	Apellidos string     `json:"apellidos"`
	Username  string     `json:"username"`
	Documento string     `json:"documento"`
	Password  *string    `json:"password,omitempty"`
	FotoURL   *string    `json:"foto_url,omitempty"`
	Telefono  *string    `json:"telefono,omitempty"`
	Correo    *string    `json:"correo,omitempty"`
	FechaNac  *time.Time `json:"fecha_nac,omitempty"`
	Domicilio *string    `json:"domicilio,omitempty"`
	Roles     []string   `json:"roles"`
}

type Personas struct {
	ID         string    `json:"id"`
	Nombres    string    `json:"nombres"`
	Apellidos  string    `json:"apellidos"`
	Telefono   string    `json:"telefono"`
	Correo     string    `json:"correo"`
	Direccion  string    `json:"direccion"`
	Tipo       string    `json:"tipo"`
	Registrado time.Time `json:"registrado"`
}

type Productos struct {
	ID            string    `json:"id"`
	Nombre        string    `json:"nombre"`
	Codigo        string    `json:"codigo"`
	UnidadMedida  string    `json:"unidad_medida"`
	PrecioEntrada float64   `json:"precio_entrada"`
	PrecioSalida  float64   `json:"precio_salida"`
	CategoriaID   string    `json:"categoria_id"`
	Registrado    time.Time `json:"registrado"`
}

type Rol struct {
	ID     string `json:"id"`
	Nombre string `json:"nombre"`
	Bit    int    `json:"bit"`
}

type RolPermiso struct {
	Metodo      string `json:"metodo"`
	Descripcion string `json:"descripcion"`
	//  los roles que tienen acceso a este permiso, expresado en suma sumaria << bits
	RolBits int `json:"rol_bits"`
}

type RolResponse struct {
	ID       string `json:"id"`
	Nombre   string `json:"nombre"`
	Bit      int    `json:"bit"`
	Permisos int    `json:"permisos"`
	Usuarios int    `json:"usuarios"`
}

type RolesUserResponse struct {
	ID       string        `json:"id"`
	Nombre   string        `json:"nombre"`
	Bit      int           `json:"bit"`
	Permisos []*RolPermiso `json:"permisos"`
}

type Tokens struct {
	Username   string    `json:"username"`
	Token      string    `json:"token"`
	Registrado time.Time `json:"registrado"`
}

type Transacciones struct {
	ID          string    `json:"id"`
	Tipo        string    `json:"tipo"`
	Descripcion string    `json:"descripcion"`
	PersonaID   string    `json:"persona_id"`
	UsuarioID   string    `json:"usuario_id"`
	Registrado  time.Time `json:"registrado"`
}

type Ubicaciones struct {
	ID         string    `json:"id"`
	AlmacenID  string    `json:"almacen_id"`
	ProductoID string    `json:"producto_id"`
	Cantidad   int       `json:"cantidad"`
	Registrado time.Time `json:"registrado"`
}

type UpdateRol struct {
	ID       string   `json:"id"`
	Nombre   string   `json:"nombre"`
	Permisos []string `json:"permisos"`
}

type UpdateUsuario struct {
	ID        string     `json:"id"`
	Nombres   string     `json:"nombres"`
	Apellidos string     `json:"apellidos"`
	Username  string     `json:"username"`
	Documento string     `json:"documento"`
	Password  *string    `json:"password,omitempty"`
	FotoURL   *string    `json:"foto_url,omitempty"`
	Telefono  *string    `json:"telefono,omitempty"`
	Correo    *string    `json:"correo,omitempty"`
	FechaNac  *time.Time `json:"fecha_nac,omitempty"`
	Domicilio *string    `json:"domicilio,omitempty"`
	Roles     []string   `json:"roles"`
}

type Usuario struct {
	ID         string     `json:"id"`
	Nombres    string     `json:"nombres"`
	Apellidos  string     `json:"apellidos"`
	Username   string     `json:"username"`
	Telefono   *string    `json:"telefono,omitempty"`
	Documento  string     `json:"documento"`
	Correo     *string    `json:"correo,omitempty"`
	FotoURL    *string    `json:"foto_url,omitempty"`
	FechaNac   *time.Time `json:"fecha_nac,omitempty"`
	Domicilio  *string    `json:"domicilio,omitempty"`
	Registrado time.Time  `json:"registrado"`
	Estado     bool       `json:"estado"`
}

type UsuarioLogin struct {
	ID         string     `json:"id"`
	Nombres    string     `json:"nombres"`
	Apellidos  string     `json:"apellidos"`
	Username   string     `json:"username"`
	FotoURL    *string    `json:"foto_url,omitempty"`
	Telefono   *string    `json:"telefono,omitempty"`
	Correo     *string    `json:"correo,omitempty"`
	Documento  string     `json:"documento"`
	FechaNac   *time.Time `json:"fecha_nac,omitempty"`
	Domicilio  *string    `json:"domicilio,omitempty"`
	Registrado time.Time  `json:"registrado"`
	Estado     bool       `json:"estado"`
	Dataname   string     `json:"dataname"`
	RolID      string     `json:"rol_id"`
	Rol        string     `json:"rol"`
	Exp        string     `json:"exp"`
}

type UsuariosResponse struct {
	ID         string     `json:"id"`
	Nombres    string     `json:"nombres"`
	Apellidos  string     `json:"apellidos"`
	Username   string     `json:"username"`
	FotoURL    *string    `json:"foto_url,omitempty"`
	Telefono   *string    `json:"telefono,omitempty"`
	Documento  string     `json:"documento"`
	FechaNac   *time.Time `json:"fecha_nac,omitempty"`
	Domicilio  *string    `json:"domicilio,omitempty"`
	Correo     *string    `json:"correo,omitempty"`
	Registrado time.Time  `json:"registrado"`
	Estado     bool       `json:"estado"`
	Dataname   string     `json:"dataname"`
	Roles      []*Rol     `json:"roles"`
}
